CREATE TABLE public.contacts
(
  id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  account_id TEXT, 
  active_tracker_count INTEGER, 
  assistant_name TEXT,
  assistant_phone TEXT,
  birthdate DATE,
  can_allow_portal_self_reg BOOLEAN, 
  contact_id TEXT,
  contact_name TEXT,
  created_by_id TEXT,
  created_date TIMESTAMP WITH TIME ZONE,
  currency_iso_code TEXT,
  department TEXT,
  do_not_call BOOLEAN, 
  email TEXT,
  external_id TEXT,
  fax TEXT,
  first_name TEXT,
  has_opted_out_of_email BOOLEAN, 
  has_opted_out_of_fax BOOLEAN, 
  has_privacy_hold BOOLEAN, 
  home_phone TEXT,
  individual_id TEXT,
  is_deleted BOOLEAN, 
  is_email_bounced BOOLEAN, 
  is_locked BOOLEAN, 
  is_person_account BOOLEAN, 
  is_priority_record BOOLEAN, 
  last_activity_date DATE,
  last_modified_by_id TEXT,
  last_modified_date TIMESTAMP WITH TIME ZONE,
  last_name TEXT,
  lead_source TEXT,
  mailing_city TEXT,
  mailing_country TEXT,
  mailing_postal_code TEXT,
  mailing_state TEXT,
  mailing_street TEXT,
  may_edit BOOLEAN, 
  middle_name TEXT,
  mobile_phone TEXT,
  other_city TEXT,
  other_country TEXT,
  other_phone TEXT,
  other_postal_code TEXT,
  other_state TEXT,
  other_street TEXT,
  owner_id TEXT,
  phone TEXT,
  photo_url TEXT,
  record_type_id TEXT,
  salutation TEXT,
  suffix TEXT,
  system_mod_stamp TIMESTAMP WITH TIME ZONE,
  title TEXT
);

CREATE INDEX contacts_id_idx ON contacts (id);
